learning_rate: 0.001
gamma: 0.99

policy:
  mode: epsilon_greedy
  epsilon: 0.1
  epsilon_decay: 0.995
  epsilon_min: 0.001

curiosity:
  beta: 4.0
  decay: 0.995

trainer:
  gamma: 0.99
  target_update_freq: 15000
  save_path: "models/mlp.pth"


replay_buffer:
  buffer_size: 15000
  batch_size: 32
  min_buffer_size: 500